### ISSUE TITLE
Set up user registration

### ISSUE THREAD

**Issue by alicejeeunlee** [alicejeeunlee/e-commerce-app#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Add the logic for handling registration of new users.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Registering a user is an important process in any app. Your registration process can use as much or as little data about the user as you’d like, but make sure to at least include an identifier such as a username as well as a password. Additionally, make sure to handle edge cases in your handler such as attempts to register users that already exist. 

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] Update server/index.js to POST '/registration/sign-up' new user information to ecommerce database.
  - [ ] Store password as hashedPassword using argon2.
- [ ]  Update server/index.js to handle POST request to '/registration/sign-in'.
  - [ ]  Select userId and hashedPassword from database where email matches email sent in request body.
  - [ ]  Verify that password sent in req.body matches hashedPassword in database.
  - [ ]  Make payload object with userId and name and token signed with token secret.
  - [ ]  Send response to client.
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### 🧑‍⚕️ Clean Up Tasks

- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
